// Generated by GitHub Copilot
import { useEffect, useState } from 'react'
import { NavLink } from 'react-router-dom'
import './FoodItemManager.css'

// Generated by GitHub Copilot
/**
 * Builds the initial FoodItemBean form model.
 * @returns {{ id: string, name: string, category: string, price: string, available: boolean }}
 */
function createInitialField() {
  return {
    id: '',
    name: '',
    category: '',
    price: '',
    available: true,
  }
}

// Generated by GitHub Copilot
/**
 * Converts FoodItemBean form values into an x-www-form-urlencoded payload.
 * Sends only non-empty id while always sending required validated fields.
 * @param {{ id: string, name: string, category: string, price: string, available: boolean }} field
 * @returns {URLSearchParams}
 */
function buildFormPayload(field) {
  const payload = new URLSearchParams()

  if (field.id.trim().length > 0) {
    payload.append('id', field.id.trim())
  }

  payload.append('name', field.name.trim())
  payload.append('category', field.category.trim())
  payload.append('price', field.price)
  payload.append('available', String(field.available))

  return payload
}

// Generated by GitHub Copilot
/**
 * Normalizes unknown API errors into a message safe for UI display.
 * @param {unknown} error
 * @returns {string}
 */
function toFriendlyError(error) {
  if (error instanceof Error) {
    return error.message
  }

  return 'Unable to reach the server. Verify backend URL and try again.'
}

// Generated by GitHub Copilot
/**
 * Builds stable table columns from all object keys in the response list.
 * @param {Array<Record<string, unknown>>} items
 * @returns {string[]}
 */
function deriveColumns(items) {
  const keys = new Set()

  for (const item of items) {
    for (const key of Object.keys(item)) {
      keys.add(key)
    }
  }

  return Array.from(keys)
}

// Generated by GitHub Copilot
/**
 * Joins a base URL and controller path without duplicating slashes.
 * @param {string} baseUrl
 * @param {string} path
 * @returns {string}
 */
function buildEndpoint(baseUrl, path) {
  return `${baseUrl.trim().replace(/\/$/, '')}${path}`
}

// Generated by GitHub Copilot
/**
 * Food item view that consumes Spring endpoints:
 * GET /food/list and POST /food/save.
 * Uses URL-encoded form body to support @ModelAttribute binding.
 * @param {{ view: 'add' | 'list' }} props
 * @returns {JSX.Element}
 */
function FoodItemManager({ view }) {
  const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8090'
  const [field, setField] = useState(() => createInitialField())
  const [items, setItems] = useState([])
  const [status, setStatus] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const columns = deriveColumns(items)

  // Generated by GitHub Copilot
  /**
   * Updates one FoodItemBean form property.
   * @param {'id' | 'name' | 'category' | 'price' | 'available'} prop
   * @param {string | boolean} value
   */
  function updateField(prop, value) {
    setField((current) => ({ ...current, [prop]: value }))
  }

  // Generated by GitHub Copilot
  /**
   * Resets the add form after a successful save.
   */
  function resetFields() {
    setField(createInitialField())
  }

  // Generated by GitHub Copilot
  /**
   * Calls GET /food/list and updates the list table.
   */
  async function fetchFoodItems() {
    setIsLoading(true)
    setStatus('Loading food items...')

    try {
      const response = await fetch(buildEndpoint(baseUrl, '/food/list'))
      if (!response.ok) {
        throw new Error(`List failed with status ${response.status}`)
      }

      const data = await response.json()
      setItems(Array.isArray(data) ? data : [])
      setStatus('Food items loaded.')
    } catch (error) {
      setStatus(toFriendlyError(error))
    } finally {
      setIsLoading(false)
    }
  }

  // Generated by GitHub Copilot
  /**
   * Submits URL-encoded fields to POST /food/save for @ModelAttribute binding.
   * @param {import('react').FormEvent<HTMLFormElement>} event
   */
  async function handleSave(event) {
    event.preventDefault()

    setIsLoading(true)
    setStatus('Saving food item...')

    try {
      const response = await fetch(buildEndpoint(baseUrl, '/food/save'), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
        },
        body: buildFormPayload(field).toString(),
      })

      const responseText = await response.text()
      if (!response.ok) {
        throw new Error(responseText || `Save failed with status ${response.status}`)
      }

      setStatus(responseText || 'Food item added successfully.')
      resetFields()
      await fetchFoodItems()
    } catch (error) {
      setStatus(toFriendlyError(error))
    }
  }

  useEffect(() => {
    if (view === 'list') {
      fetchFoodItems()
    }
  }, [view])

  return (
    <main className="food-app">
      <header className="food-header">
        <h1>CafeConnect</h1>
        <nav className="quick-links" aria-label="Food item sections">
          <NavLink to="/add-fooditem">Add Food Item</NavLink>
          <NavLink to="/get-fooditems">Get Food Items</NavLink>
        </nav>
      </header>

      {view === 'add' ? (
        <section id="add-fooditem" className="food-panel" aria-labelledby="save-title">
        <h2 id="save-title">Add Food Item</h2>
        <form onSubmit={handleSave}>
          <div className="field-grid" role="group" aria-label="Food item fields">
            <div className="field-row">
              <label htmlFor="food-id">Id (optional)</label>
              <input
                id="food-id"
                type="number"
                min="1"
                value={field.id}
                onChange={(event) => updateField('id', event.target.value)}
                placeholder="Auto-generated if empty"
              />
            </div>

            <div className="field-row">
              <label htmlFor="food-name">Name</label>
              <input
                id="food-name"
                type="text"
                value={field.name}
                onChange={(event) => updateField('name', event.target.value)}
                placeholder="Food name"
                required
              />
            </div>

            <div className="field-row">
              <label htmlFor="food-category">Category</label>
              <input
                id="food-category"
                type="text"
                value={field.category}
                onChange={(event) => updateField('category', event.target.value)}
                placeholder="Starter / Main course / Dessert"
                required
              />
            </div>

            <div className="field-row">
              <label htmlFor="food-price">Price</label>
              <input
                id="food-price"
                type="number"
                min="1"
                step="0.01"
                value={field.price}
                onChange={(event) => updateField('price', event.target.value)}
                placeholder="1.00"
                required
              />
            </div>

            <div className="field-row field-row--checkbox">
              <input
                id="food-available"
                type="checkbox"
                checked={field.available}
                onChange={(event) => updateField('available', event.target.checked)}
              />
              <label htmlFor="food-available">Available (must be checked)</label>
            </div>
          </div>

          <div className="action-row">
            <button className="btn btn--accent" type="submit" disabled={isLoading}>
              Save Food Item
            </button>
          </div>
        </form>
        {status ? <p className="status" role="status">{status}</p> : null}
      </section>
      ) : null}

      {view === 'list' ? (
        <section id="get-fooditems" className="food-panel" aria-labelledby="list-title">
        <div className="list-head">
          <h2 id="list-title">Food Items</h2>
          <button className="btn" type="button" onClick={fetchFoodItems} disabled={isLoading}>
            Refresh List
          </button>
        </div>

        {status ? <p className="status" role="status">{status}</p> : null}

        {items.length === 0 ? (
          <p className="empty">No records loaded yet.</p>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  {columns.map((column) => (
                    <th key={column} scope="col">{column}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {items.map((item, rowIndex) => (
                  <tr key={`${rowIndex}-${String(item.id ?? 'row')}`}>
                    {columns.map((column) => (
                      <td key={`${rowIndex}-${column}`}>{String(item[column] ?? '')}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
      ) : null}
    </main>
  )
}

export default FoodItemManager
